# Generated by Django 4.2.7 on 2026-06-01 03:01

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_meeting_error_message_alter_meeting_status'),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE EXTENSION IF NOT EXISTS vector;',
            reverse_sql='DROP EXTENSION IF EXISTS vector;',
        ),
        migrations.CreateModel(
            name='TranscriptChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The chunk text (200-300 words).')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384, help_text='384-dim embedding from all-MiniLM-L6-v2.')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.meeting')),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_embedding_idx', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
